# Что бы использовать этот скрипт:
# 1. На сервере используйте команду `aedumpenchants` с консоли
# 2. Из `plugins/Bukkript/logs/commands/ae_dump_enchants.log` скопируйте json
# 3. Вставьте json в `data/enchants.json`
# 4. Запустите этот скрипт

import json

# Example enchantment
# {
#     "appliesTo": "Элитры",
#     "highestLevel": 5,
#     "description": "Шанс отравить противника и обретение регенерации.",
#     "display": "Приговор"
# }
groupToNames = {
    "SIMPLE": "Обычный",
    "UNIQUE": "Редкий",
    "ELITE": "Элитный",
    "ULTIMATE": "Высший",
    "LEGENDARY": "Легендарный",
    "FABLED": "Мифический",
}


def main():
    with open("data/enchants.json", encoding="utf-8") as f:
        data = json.load(f)
    md_string = "[//]: # (generated by scripts/gen_enchants.py)\n\n"
    # the keys are group ids, values are enchantments
    for group in groupToNames.keys():
        group_name = groupToNames[group]
        md_string += f"=== \"{group_name}\""
        enchantment_string = "\n"
        for enchantment in data[group]:
            enchantment_string += f"    !!! enchants-{group.lower()} \"{enchantment['display']}\"\n"
            enchantment_string += f"        {enchantment['description']}<br><br>"
            enchantment_string += f"**Применяется к:** {enchantment['appliesTo']}<br>"
            enchantment_string += f"**Максимальный уровень:** {enchantment['highestLevel']}\n"
        md_string += enchantment_string

    with open("../docs/enchantments.md", "w", encoding="utf-8") as f:
        f.write(md_string)


main()
